version: '3.8'

services:
  front-end:
    container_name: front-end
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run dev
    ports:
      - 3000:3000
      - 9229:9299
    volumes:
      - ./:/usr/src/app
    networks:
      - default
    environment:
      BASE_API_URI: testing.com
    
volumes:
  services:

networks:
  default: